### ISSUE TITLE
[Help Wanted] 

### ISSUE THREAD

**Issue by MrAugu** [MrAugu/enet-client#2]
Basically, after i am receiving the login request packet from the server, i send a type 2 tank packet with the login info but server is not responding back with anything. Any help is welcomed.

**Comment by Enpax** [comment]
int packet::get_message_type(ENetPacket* packet) {
	if (packet->dataLength > 3u) {
		return *(packet->data);
	} else {
		return -30;
	}
}

**Comment by Enpax** [comment]
can you add creds.h to ur repo let me build and see whats error

**Comment by MrAugu** [comment]
Creds.h store growtopia login info.
```cpp
#pragma once

#include <string>

using namespace std;

namespace creds {
	string gtUsername = "<gt_username>";
	string gtPassword = "<gt_password>";
}
```



> int packet::get_message_type(ENetPacket* packet) {
> if (packet->dataLength > 3u) {
> return *(packet->data);
> } else {
> return -30;
> }
> }

This works properly -30 is an invalid type which i will handle at some point, there are no errors, the tank packet is sent to the server but the server never sends anything back.

**Comment by Enpax** [comment]
what is the error ? can you give me more

**Comment by Enpax** [comment]
error happen because u need create http client

**Comment by Enpax** [comment]
https://github.com/ama6nen/enetproxy/blob/master/proxy/server.cpp

**Comment by MrAugu** [comment]
There is no error, this IS NOT a packet proxy!! This is a client that logins into the server on its own!!
